export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';

export const INCREASE = 'INCREASE';

export const PRODUCTS_ADD_ALL = 'PRODUCTS_ADD_ALL';
export const PRODUCTS_SET_LOADING = 'PRODUCTS_SET_LOADING';
